[package]
name = "kaspa-index-core"
description = "Kaspa index core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
thiserror.workspace = true
kaspa-consensus-core.workspace = true
kaspa-utils.workspace = true
kaspa-notify.workspace = true
async-channel.workspace = true
async-trait.workspace = true
log.workspace = true
serde.workspace = true
futures.workspace = true
triggered.workspace = true
derive_more.workspace = true
paste.workspace = true

[dev-dependencies]
# parking_lot.workspace = true
# tokio = { workspace = true, features = ["rt", "macros"] }
# rand = {workspace = true,  features = [ "small_rng" ]}