[package]
name = "kaspa-addressmanager"
description = "Kaspa address manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
igd-next.workspace = true
itertools.workspace = true
kaspa-consensus-core.workspace = true
kaspa-core.workspace = true
kaspa-database.workspace = true
kaspa-utils.workspace = true
local-ip-address.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
statrs.workspace = true
statest.workspace = true
