[package]
name = "kaspa-wallet"
description = "Kaspa wallet"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
async-std.workspace = true
async-trait.workspace = true
kaspa-cli.workspace = true
tokio.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true

[lints]
workspace = true
