[package]
name = "zk-covenant-common"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
kaspa-consensus-core = { path = "../../consensus/core" }
kaspa-txscript = { path = "../../crypto/txscript" }

anyhow = "1.0"
ark-bn254 = "0.5.0"
ark-groth16 = "0.5.0"
ark-serialize = "0.5.0"
bincode = "1.3"
risc0-groth16 = "3.0.3"
risc0-zkvm = { version = "3.0.4", default-features = true }
