[package]
name = "consensus-notify"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
thiserror.workspace = true
consensus-core.workspace = true
kaspa-notify.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
async-channel.workspace = true
log.workspace = true
futures = "0.3.25"
triggered = "0.1"