[package]
name = "kaspa-consensusmanager"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
tokio.workspace = true
log.workspace = true
parking_lot.workspace = true
itertools.workspace = true
rand.workspace = true
futures-util.workspace = true
futures.workspace = true
duration-string = "0.2.0"
arc-swap = { version = "1.6.0", features = ["weak"] }
