[package]
name = "kaspa-p2p-mining"
description = "Kaspa p2p mining"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-mining-errors.workspace = true
kaspa-hashes.workspace = true
kaspa-math.workspace = true
kaspa-p2p-lib.workspace = true
kaspa-utils.workspace = true
kaspa-utils-tower.workspace = true
log.workspace = true
tokio.workspace = true

[lints]
workspace = true
