[package]
name = "kaspa-math"
description = "Kaspa misc math library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
include.workspace = true

[dependencies]
serde.workspace = true
faster-hex.workspace = true
borsh.workspace = true
malachite-nz = "0.3"
malachite-base = "0.3"
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true
js-sys.workspace = true
kaspa-utils.workspace = true
thiserror.workspace = true
workflow-wasm.workspace = true

workflow-log.workspace = true

[dev-dependencies]
rand_chacha.workspace = true
criterion.workspace = true

[[bench]]
name = "bench"
harness = false
