[package]
name = "kaspa-wrpc-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
kaspa-consensus-core.workspace = true
kaspa-rpc-core.workspace = true
kaspa-grpc-client.workspace = true
kaspa-wrpc-server.workspace = true
tokio.workspace = true
thiserror.workspace = true
clap.workspace = true
workflow-core.workspace = true
workflow-rpc.workspace = true
workflow-log.workspace = true
async-trait.workspace = true
kaspa-rpc-macros.workspace = true
num_cpus.workspace = true


[package.metadata.emanate.build]
folder = "setup"
