[package]
name = "zk-covenant-inline-core"
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"]}
#blake2b_simd.workspace = true
#borsh = { workspace = true, default-features = false }
#smallvec = {  workspace = true, features = ["const_generics"] }

[lints]
workspace = true
