[package]
name = "kaspa-wrpc-covenants-native-asset"
description = "Kaspa Covenants Native Asset example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kaspa-wrpc-covenants-native-asset-vm"
path = "src/native_asset_vm.rs"

[dependencies]
futures.workspace = true
kaspa-rpc-core.workspace = true
kaspa-wallet-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-hashes.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-addresses.workspace = true
kaspa-txscript.workspace = true
kaspa-txscript-errors.workspace = true
kaspa-bip32.workspace = true
kaspa-wallet-keys.workspace = true
tokio.workspace = true
thiserror.workspace = true
rand.workspace = true

[lints]
workspace = true
