[package]
name = "kaspa-grpc-core"
description = "Kaspa gRPC core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kaspa-utils.workspace = true
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
faster-hex.workspace = true
async-channel.workspace = true
log.workspace = true
rand.workspace = true
paste.workspace = true
regex.workspace = true
async-trait = "0.1.57"
futures = { version = "0.3" }
tonic = { version = "0.10", features = ["tls", "gzip"] }
prost = { version = "0.12" }
h2 = "0.3"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"
async-stream = "0.3"
triggered = "0.1"

[build-dependencies]
tonic-build = { version = "0.10", features = ["prost"] }
