[package]
name = "kaspa-p2p-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[lib]
path = "./src/lib.rs"

[[bin]]
name = "kaspa_p2p_client"
path = "./src/bin/client.rs"

[[bin]]
name = "kaspa_p2p_server"
path = "./src/bin/server.rs"

[dependencies]
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-addressmanager.workspace = true
kaspa-mining.workspace = true
kaspa-hashes.workspace = true
kaspa-math.workspace = true

log.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
itertools.workspace = true
uuid.workspace = true

futures = { version = "0.3", default-features = false, features = ["alloc"] }
prost = "0.11"
ctrlc = "3.2"
tokio = { version = "1.21.2", features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = { version = "0.9.1", features = ["tls", "gzip"] }
h2 = "0.3"

[build-dependencies]
tonic-build = { version = "0.9.1", features = ["prost"] }

[dev-dependencies]
hex = "0.4.3"
