[package]
name = "p2p-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[lib]
path = "./src/lib.rs"

[[bin]]
name = "kaspa_p2p_client"
path = "./src/bin/client.rs"

[[bin]]
name = "kaspa_p2p_server"
path = "./src/bin/server.rs"

[dependencies]
kaspa-core.workspace = true

log.workspace = true
thiserror.workspace = true
parking_lot.workspace = true

futures = { version = "0.3", default-features = false, features = ["alloc"] }
prost = "0.11"
ctrlc = "3.2"
tokio = { version = "1.21.2", features = [ "rt-multi-thread", "macros", "signal" ]}
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = { version = "0.8.2", features = ["tls", "gzip"] }
h2 = "0.3"
uuid = { version = "1.2.2", features = ["v4","fast-rng"] }
async-stream = "0.3.3"

[build-dependencies]
tonic-build = { version = "0.8.2", features = ["prost"] }
