[package]
name = "kaspa-p2p-flows"
description = "Kaspa p2p flows"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaspa-core.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-p2p-lib.workspace = true
kaspa-utils.workspace = true
kaspa-hashes.workspace = true
kaspa-muhash.workspace = true
kaspa-connectionmanager.workspace = true
kaspa-addressmanager.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-mining.workspace = true
kaspa-notify.workspace = true

parking_lot.workspace = true
rand.workspace = true
thiserror.workspace = true
log.workspace = true
itertools.workspace = true
indexmap.workspace = true
async-trait.workspace = true

futures = { version = "0.3", default-features = false, features = ["alloc"] }
tokio = { version = "1.21.2", features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
tokio-stream = { version = "0.1.11", features = ["net"] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }
