[package]
name = "kaspa-consensus-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
kaspa-muhash.workspace = true
kaspa-merkle.workspace = true
kaspa-math.workspace = true
kaspa-addresses.workspace = true
kaspa-utils.workspace = true
kaspa-txscript-errors.workspace = true

thiserror.workspace = true
serde.workspace = true
faster-hex.workspace = true
smallvec.workspace = true
borsh.workspace = true
futures-util.workspace = true
itertools.workspace = true
cfg-if.workspace = true
getrandom.workspace = true

secp256k1 = { version = "0.24", features = ["global-context", "rand-std"] }
