[package]
name = "kaspa-wallet-cli-wasm"
description = "Kaspa CLI wallet for WASM"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait.workspace = true
js-sys.workspace = true
kaspa-cli.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true
workflow-wasm.workspace = true

[lints]
workspace = true