[package]
name = "kaspa-utils"
description = "Kaspa utilities"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
borsh.workspace = true
cfg-if.workspace = true
event-listener.workspace = true
faster-hex.workspace = true
ipnet.workspace = true
itertools.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
triggered.workspace = true
uuid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rlimit.workspace = true
futures.workspace = true
tower-http.workspace = true
tower.workspace = true
hyper.workspace = true
pin-project-lite.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros"]}

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "time", "macros"]}
bincode.workspace = true
serde_json.workspace = true
async-trait.workspace = true
futures-util.workspace = true
criterion.workspace = true
rand.workspace = true

[[bench]]
name = "bench"
harness = false
