[package]
name = "kaspa-utils"
description = "Kaspa utilities"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
uuid.workspace = true
serde.workspace = true
borsh.workspace = true
faster-hex.workspace = true
smallvec.workspace = true
itertools.workspace = true
thiserror.workspace = true
cfg-if.workspace = true

triggered.workspace = true
event-listener.workspace = true
ipnet.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rlimit = "0.10.1"

[dev-dependencies]
bincode.workspace = true
serde_json.workspace = true
async-trait.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros"] }
criterion.workspace = true
rand.workspace = true

[[bench]]
name = "bench"
harness = false
