[package]
name = "kaspa-rpc-service"
description = "Kaspa RPC service"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-addresses.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-consensus.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-core.workspace = true
kaspa-index-core.workspace = true
kaspa-math.workspace = true
kaspa-mining.workspace = true
kaspa-notify.workspace = true
kaspa-p2p-flows.workspace = true
kaspa-p2p-lib.workspace = true
kaspa-perf-monitor.workspace = true
kaspa-rpc-core.workspace = true
kaspa-txscript.workspace = true
kaspa-utils.workspace = true
kaspa-utxoindex.workspace = true
kaspa-wrpc-core.workspace = true

async-trait.workspace = true
log.workspace = true
tokio.workspace = true