[package]
name = "kaspa-utils-tower"
description = "Kaspa utilities and middleware for Tower HTTP"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
cfg-if.workspace = true
log.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures.workspace = true
hyper.workspace = true
pin-project-lite.workspace = true
tokio.workspace = true
tower-http.workspace = true
tower.workspace = true