[package]
name = "kaspa-utxoindex"
description = "Kaspa UTXO index"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
kaspa-consensus.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-notify.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
kaspa-index-core.workspace = true
kaspa-database.workspace = true

thiserror.workspace = true
log.workspace = true
rocksdb.workspace = true
serde.workspace = true
parking_lot.workspace = true
futures.workspace = true

[dev-dependencies]
kaspa-consensus.workspace = true
rand = { workspace = true, features = ["small_rng"] }
